// <auto-generated />
using System;
using JPGZService.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JPGZService.Migrations.JPGZServiceDb
{
    [DbContext(typeof(JPGZServiceDbContext))]
    [Migration("20190703085948_init_sqlserver")]
    partial class init_sqlserver
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Abp.Auditing.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrowserInfo");

                    b.Property<string>("ClientIpAddress");

                    b.Property<string>("ClientName");

                    b.Property<string>("CustomData");

                    b.Property<string>("Exception");

                    b.Property<int>("ExecutionDuration");

                    b.Property<DateTime>("ExecutionTime");

                    b.Property<int?>("ImpersonatorTenantId");

                    b.Property<long?>("ImpersonatorUserId");

                    b.Property<string>("MethodName");

                    b.Property<string>("Parameters");

                    b.Property<string>("ReturnValue");

                    b.Property<string>("ServiceName");

                    b.Property<int?>("TenantId");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.ToTable("AbpAuditLogs");
                });

            modelBuilder.Entity("JPGZService.SqlServertestModel.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Cdate");

                    b.Property<string>("CoverPicture");

                    b.Property<int?>("DataOrganizeID");

                    b.Property<bool?>("IsDelete");

                    b.Property<int>("IsPublish");

                    b.Property<bool?>("IsTopping");

                    b.Property<string>("Nattachment");

                    b.Property<string>("Ncontent");

                    b.Property<int?>("NewObject");

                    b.Property<string>("Ntitle");

                    b.Property<int?>("Ntype");

                    b.Property<string>("SysNattachment");

                    b.Property<int?>("UserID");

                    b.Property<int?>("UserType");

                    b.HasKey("Id");

                    b.ToTable("tb_News");
                });
#pragma warning restore 612, 618
        }
    }
}
